remote_theme: just-the-docs/just-the-docs
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Overview
    docs:
      name: Gameplay
    tutorials:
      name: Tutorials